on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release version"
        type: choice
        required: true
        options:
          - patch
          - minor
          - major

name: Bump Extension Version

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: extension
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - id: bump-version
        run: |
          npm version ${{ inputs.release }} | xargs -I% echo "::set-output name=version::%"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: release ${{ steps.bump-version.outputs.version }}
          tagging_message: ${{ steps.bump-version.outputs.version }}
